// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: internal/event-processor/proto/task.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskType int32

const (
	TaskType_KEY_ENABLE    TaskType = 0
	TaskType_KEY_DISABLE   TaskType = 1
	TaskType_KEY_DELETE    TaskType = 2
	TaskType_KEY_ROTATE    TaskType = 3
	TaskType_SYSTEM_LINK   TaskType = 4
	TaskType_SYSTEM_UNLINK TaskType = 5
	TaskType_SYSTEM_SWITCH TaskType = 6
	TaskType_KEY_DETACH    TaskType = 7
)

// Enum value maps for TaskType.
var (
	TaskType_name = map[int32]string{
		0: "KEY_ENABLE",
		1: "KEY_DISABLE",
		2: "KEY_DELETE",
		3: "KEY_ROTATE",
		4: "SYSTEM_LINK",
		5: "SYSTEM_UNLINK",
		6: "SYSTEM_SWITCH",
		7: "KEY_DETACH",
	}
	TaskType_value = map[string]int32{
		"KEY_ENABLE":    0,
		"KEY_DISABLE":   1,
		"KEY_DELETE":    2,
		"KEY_ROTATE":    3,
		"SYSTEM_LINK":   4,
		"SYSTEM_UNLINK": 5,
		"SYSTEM_SWITCH": 6,
		"KEY_DETACH":    7,
	}
)

func (x TaskType) Enum() *TaskType {
	p := new(TaskType)
	*p = x
	return p
}

func (x TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_event_processor_proto_task_proto_enumTypes[0].Descriptor()
}

func (TaskType) Type() protoreflect.EnumType {
	return &file_internal_event_processor_proto_task_proto_enumTypes[0]
}

func (x TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskType.Descriptor instead.
func (TaskType) EnumDescriptor() ([]byte, []int) {
	return file_internal_event_processor_proto_task_proto_rawDescGZIP(), []int{0}
}

// Wrapped proto for Orbital TaskRequest.data.
type Data struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TaskType TaskType               `protobuf:"varint,5,opt,name=task_type,json=taskType,proto3,enum=proto.TaskType" json:"task_type,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*Data_KeyAction
	//	*Data_SystemAction
	Data          isData_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_internal_event_processor_proto_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_internal_event_processor_proto_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_internal_event_processor_proto_task_proto_rawDescGZIP(), []int{0}
}

func (x *Data) GetTaskType() TaskType {
	if x != nil {
		return x.TaskType
	}
	return TaskType_KEY_ENABLE
}

func (x *Data) GetData() isData_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Data) GetKeyAction() *KeyAction {
	if x != nil {
		if x, ok := x.Data.(*Data_KeyAction); ok {
			return x.KeyAction
		}
	}
	return nil
}

func (x *Data) GetSystemAction() *SystemAction {
	if x != nil {
		if x, ok := x.Data.(*Data_SystemAction); ok {
			return x.SystemAction
		}
	}
	return nil
}

type isData_Data interface {
	isData_Data()
}

type Data_KeyAction struct {
	KeyAction *KeyAction `protobuf:"bytes,10,opt,name=key_action,json=keyAction,proto3,oneof"`
}

type Data_SystemAction struct {
	SystemAction *SystemAction `protobuf:"bytes,20,opt,name=system_action,json=systemAction,proto3,oneof"`
}

func (*Data_KeyAction) isData_Data() {}

func (*Data_SystemAction) isData_Data() {}

// TaskType KEY_ENABLE, KEY_DISABLE, KEY_DELETE, KEY_ROTATE
type KeyAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,10,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,20,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CmkRegion     string                 `protobuf:"bytes,30,opt,name=cmk_region,json=cmkRegion,proto3" json:"cmk_region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyAction) Reset() {
	*x = KeyAction{}
	mi := &file_internal_event_processor_proto_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyAction) ProtoMessage() {}

func (x *KeyAction) ProtoReflect() protoreflect.Message {
	mi := &file_internal_event_processor_proto_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyAction.ProtoReflect.Descriptor instead.
func (*KeyAction) Descriptor() ([]byte, []int) {
	return file_internal_event_processor_proto_task_proto_rawDescGZIP(), []int{1}
}

func (x *KeyAction) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *KeyAction) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *KeyAction) GetCmkRegion() string {
	if x != nil {
		return x.CmkRegion
	}
	return ""
}

// TaskType SYSTEM_LINK, SYSTEM_UNLINK, SYSTEM_SWITCH
type SystemAction struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SystemId          string                 `protobuf:"bytes,10,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
	SystemRegion      string                 `protobuf:"bytes,12,opt,name=system_region,json=systemRegion,proto3" json:"system_region,omitempty"`
	SystemType        string                 `protobuf:"bytes,15,opt,name=system_type,json=systemType,proto3" json:"system_type,omitempty"`
	KeyIdFrom         string                 `protobuf:"bytes,20,opt,name=key_id_from,json=keyIdFrom,proto3" json:"key_id_from,omitempty"`
	KeyIdTo           string                 `protobuf:"bytes,30,opt,name=key_id_to,json=keyIdTo,proto3" json:"key_id_to,omitempty"`
	KeyProvider       string                 `protobuf:"bytes,35,opt,name=key_provider,json=keyProvider,proto3" json:"key_provider,omitempty"`
	KeyAccessMetaData []byte                 `protobuf:"bytes,40,opt,name=key_access_meta_data,json=keyAccessMetaData,proto3" json:"key_access_meta_data,omitempty"`
	TenantId          string                 `protobuf:"bytes,50,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	TenantOwnerId     string                 `protobuf:"bytes,51,opt,name=tenant_owner_id,json=tenantOwnerId,proto3" json:"tenant_owner_id,omitempty"`
	TenantOwnerType   string                 `protobuf:"bytes,52,opt,name=tenant_owner_type,json=tenantOwnerType,proto3" json:"tenant_owner_type,omitempty"`
	CmkRegion         string                 `protobuf:"bytes,60,opt,name=cmk_region,json=cmkRegion,proto3" json:"cmk_region,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SystemAction) Reset() {
	*x = SystemAction{}
	mi := &file_internal_event_processor_proto_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemAction) ProtoMessage() {}

func (x *SystemAction) ProtoReflect() protoreflect.Message {
	mi := &file_internal_event_processor_proto_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemAction.ProtoReflect.Descriptor instead.
func (*SystemAction) Descriptor() ([]byte, []int) {
	return file_internal_event_processor_proto_task_proto_rawDescGZIP(), []int{2}
}

func (x *SystemAction) GetSystemId() string {
	if x != nil {
		return x.SystemId
	}
	return ""
}

func (x *SystemAction) GetSystemRegion() string {
	if x != nil {
		return x.SystemRegion
	}
	return ""
}

func (x *SystemAction) GetSystemType() string {
	if x != nil {
		return x.SystemType
	}
	return ""
}

func (x *SystemAction) GetKeyIdFrom() string {
	if x != nil {
		return x.KeyIdFrom
	}
	return ""
}

func (x *SystemAction) GetKeyIdTo() string {
	if x != nil {
		return x.KeyIdTo
	}
	return ""
}

func (x *SystemAction) GetKeyProvider() string {
	if x != nil {
		return x.KeyProvider
	}
	return ""
}

func (x *SystemAction) GetKeyAccessMetaData() []byte {
	if x != nil {
		return x.KeyAccessMetaData
	}
	return nil
}

func (x *SystemAction) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SystemAction) GetTenantOwnerId() string {
	if x != nil {
		return x.TenantOwnerId
	}
	return ""
}

func (x *SystemAction) GetTenantOwnerType() string {
	if x != nil {
		return x.TenantOwnerType
	}
	return ""
}

func (x *SystemAction) GetCmkRegion() string {
	if x != nil {
		return x.CmkRegion
	}
	return ""
}

var File_internal_event_processor_proto_task_proto protoreflect.FileDescriptor

const file_internal_event_processor_proto_task_proto_rawDesc = "" +
	"\n" +
	")internal/event-processor/proto/task.proto\x12\x05proto\"\xab\x01\n" +
	"\x04Data\x12,\n" +
	"\ttask_type\x18\x05 \x01(\x0e2\x0f.proto.TaskTypeR\btaskType\x121\n" +
	"\n" +
	"key_action\x18\n" +
	" \x01(\v2\x10.proto.KeyActionH\x00R\tkeyAction\x12:\n" +
	"\rsystem_action\x18\x14 \x01(\v2\x13.proto.SystemActionH\x00R\fsystemActionB\x06\n" +
	"\x04data\"^\n" +
	"\tKeyAction\x12\x15\n" +
	"\x06key_id\x18\n" +
	" \x01(\tR\x05keyId\x12\x1b\n" +
	"\ttenant_id\x18\x14 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"cmk_region\x18\x1e \x01(\tR\tcmkRegion\"\x91\x03\n" +
	"\fSystemAction\x12\x1b\n" +
	"\tsystem_id\x18\n" +
	" \x01(\tR\bsystemId\x12#\n" +
	"\rsystem_region\x18\f \x01(\tR\fsystemRegion\x12\x1f\n" +
	"\vsystem_type\x18\x0f \x01(\tR\n" +
	"systemType\x12\x1e\n" +
	"\vkey_id_from\x18\x14 \x01(\tR\tkeyIdFrom\x12\x1a\n" +
	"\tkey_id_to\x18\x1e \x01(\tR\akeyIdTo\x12!\n" +
	"\fkey_provider\x18# \x01(\tR\vkeyProvider\x12/\n" +
	"\x14key_access_meta_data\x18( \x01(\fR\x11keyAccessMetaData\x12\x1b\n" +
	"\ttenant_id\x182 \x01(\tR\btenantId\x12&\n" +
	"\x0ftenant_owner_id\x183 \x01(\tR\rtenantOwnerId\x12*\n" +
	"\x11tenant_owner_type\x184 \x01(\tR\x0ftenantOwnerType\x12\x1d\n" +
	"\n" +
	"cmk_region\x18< \x01(\tR\tcmkRegion*\x92\x01\n" +
	"\bTaskType\x12\x0e\n" +
	"\n" +
	"KEY_ENABLE\x10\x00\x12\x0f\n" +
	"\vKEY_DISABLE\x10\x01\x12\x0e\n" +
	"\n" +
	"KEY_DELETE\x10\x02\x12\x0e\n" +
	"\n" +
	"KEY_ROTATE\x10\x03\x12\x0f\n" +
	"\vSYSTEM_LINK\x10\x04\x12\x11\n" +
	"\rSYSTEM_UNLINK\x10\x05\x12\x11\n" +
	"\rSYSTEM_SWITCH\x10\x06\x12\x0e\n" +
	"\n" +
	"KEY_DETACH\x10\aB?Z=github.tools.sap/kms/cmk/internal/event-processor/proto;protob\x06proto3"

var (
	file_internal_event_processor_proto_task_proto_rawDescOnce sync.Once
	file_internal_event_processor_proto_task_proto_rawDescData []byte
)

func file_internal_event_processor_proto_task_proto_rawDescGZIP() []byte {
	file_internal_event_processor_proto_task_proto_rawDescOnce.Do(func() {
		file_internal_event_processor_proto_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_event_processor_proto_task_proto_rawDesc), len(file_internal_event_processor_proto_task_proto_rawDesc)))
	})
	return file_internal_event_processor_proto_task_proto_rawDescData
}

var file_internal_event_processor_proto_task_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_event_processor_proto_task_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_event_processor_proto_task_proto_goTypes = []any{
	(TaskType)(0),        // 0: proto.TaskType
	(*Data)(nil),         // 1: proto.Data
	(*KeyAction)(nil),    // 2: proto.KeyAction
	(*SystemAction)(nil), // 3: proto.SystemAction
}
var file_internal_event_processor_proto_task_proto_depIdxs = []int32{
	0, // 0: proto.Data.task_type:type_name -> proto.TaskType
	2, // 1: proto.Data.key_action:type_name -> proto.KeyAction
	3, // 2: proto.Data.system_action:type_name -> proto.SystemAction
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_event_processor_proto_task_proto_init() }
func file_internal_event_processor_proto_task_proto_init() {
	if File_internal_event_processor_proto_task_proto != nil {
		return
	}
	file_internal_event_processor_proto_task_proto_msgTypes[0].OneofWrappers = []any{
		(*Data_KeyAction)(nil),
		(*Data_SystemAction)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_event_processor_proto_task_proto_rawDesc), len(file_internal_event_processor_proto_task_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_event_processor_proto_task_proto_goTypes,
		DependencyIndexes: file_internal_event_processor_proto_task_proto_depIdxs,
		EnumInfos:         file_internal_event_processor_proto_task_proto_enumTypes,
		MessageInfos:      file_internal_event_processor_proto_task_proto_msgTypes,
	}.Build()
	File_internal_event_processor_proto_task_proto = out.File
	file_internal_event_processor_proto_task_proto_goTypes = nil
	file_internal_event_processor_proto_task_proto_depIdxs = nil
}
