{{- if .Values.tenantManager.deploy }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cmk.name" . }}-tenant-manager-config
  labels:
    {{- include "cmk.tenant-manager.labels" . | nindent 4 }}
immutable: {{ .Values.config.isImmutable | default false }}
data:
  config.yaml: |-
    application:
      name: tenant-manager
    {{- with .Values.config }}
      environment: {{ .environment }}
      {{- with .labels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end}}

    status:
      {{- toYaml .status | nindent 6 }}

    logger:
      {{- toYaml .logger | nindent 6 }}

    telemetry:
      {{- toYaml .telemetry | nindent 6 }}

    # Database configuration
    database:
      {{- toYaml .database | nindent 6 }}

    # Services configuration
    services:
      {{- toYaml .services | nindent 6 }}

    tenantManager:
      {{- toYaml .tenantManager | nindent 6 }}

    {{- end }}
{{- end }}
