---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tenant-manager-cli.fullname" . }}
  labels:
    {{- include "tenant-manager-cli.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
{{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
{{- end }}
  selector:
    {{- include "tenant-manager-cli.selectorLabels" . | nindent 4 }}