# syntax=docker/dockerfile:1

FROM golang:1.26 AS builder

WORKDIR /app

ENV GOCACHE=/root/.cache/go-build

RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=bind,target=. \
    CGO_ENABLED=0 \
    go build -o /bin/cmkd ./cmd/cmkd

RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=bind,target=. \
    CGO_ENABLED=0 \
    go build -o /bin/cmkctl ./cmd/cmkctl

FROM gcr.io/distroless/static-debian12:debug AS runner

COPY migrations /etc/cmk/migrations

COPY --from=builder /bin/cmkctl /bin/cmkctl
COPY --from=builder /bin/cmkd /bin/cmkd

EXPOSE 8080
