FROM alpine:3.24.1 AS builder

ARG TARGETOS
ARG TARGETARCH

COPY bin/** /binaries/
WORKDIR /binaries

RUN find . -type f ! -name "*.$TARGETOS-$TARGETARCH" -delete && \
    for f in *."$TARGETOS-$TARGETARCH"; do \
      [ -e "$f" ] && mv "$f" "${f%.$TARGETOS-$TARGETARCH}"; \
    done

# --- Final Stage ---
FROM gcr.io/distroless/static-debian12:nonroot@sha256:afa5c872c891853ca7fcf1f12c3edb23f7eeef36189728842dd51042ff57f7ab

COPY --from=builder /binaries/ /

COPY migrations /etc/cmk/migrations

USER 65532:65532