FROM alpine:3.24.1 AS builder

ARG TARGETOS
ARG TARGETARCH

COPY bin/** /binaries/
WORKDIR /binaries

RUN find . -type f ! -name "*.$TARGETOS-$TARGETARCH" -delete && \
    for f in *."$TARGETOS-$TARGETARCH"; do \
      [ -e "$f" ] && mv "$f" "${f%.$TARGETOS-$TARGETARCH}"; \
    done

# --- Final Stage ---
FROM gcr.io/distroless/static-debian12:nonroot@sha256:1b7b9f0f0e0a1d2155f531db587cc48ec26aaf97ab64364225f5bf18a054e66a

COPY --from=builder /binaries/ /

COPY migrations /etc/cmk/migrations

USER 65532:65532