sonar.exclusions=**/api/cmkapi/cmkapi.go
sonar.test.inclusions=**/*_test.go
sonar.coverage.exclusions=**/api/**,**/noop/**,**/wrapper/**,**/main.go,**/*_test.go,**/*_config.go,**/*_dto.go,**/*_model.go, **.sql,internal/api/cmkapi/cmkapi.go
sonar.cpd.exclusions=**/api/**,**/noop/**,**/wrapper/**,**/main.go,**/*_test.go,**/mocks/**,**/proto/**,**/*_generated.go,internal/api/cmkapi/cmkapi.go
