version: 3

includes:
  shared:
    taskfile: hack/common/Taskfile_service.yaml
    flatten: true
    excludes: [] # put task names in here which are overwritten in this file
    vars:
      CODE_DIRS: '{{.ROOT_DIR}}/cmd/... {{.ROOT_DIR}}/internal/... {{.ROOT_DIR}}/apis/... {{.ROOT_DIR}}/test/... {{.ROOT_DIR}}/utils/...'
      COMPONENTS: 'api-server db-migrator task-cli task-scheduler task-worker tenant-manager tenant-manager-cli'
      CHART_COMPONENTS: 'cmk'
      SKIP_VALIDATION_TESTS: "true"

