package: cmkapi
output: ./internal/api/cmk/generated/api.go
generate:
  models: true
  std-http-server: true
  strict-server: true
  embedded-spec: true
compatibility:
  always-prefix-enum-values: true