-- This file was generated by GORM DDL
-- +goose Up
CREATE TABLE IF NOT EXISTS keystore_configurations (
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	id uuid NOT NULL,
	provider varchar(50) NOT NULL,
	value jsonb NOT NULL,
	CONSTRAINT keystore_configurations_pkey PRIMARY KEY (id),
	CONSTRAINT uni_public_keystore_configurations_value UNIQUE (value)
);

CREATE TABLE IF NOT EXISTS tenants (
	domain_url varchar(128) NULL,
	schema_name varchar(63) NULL,
	id varchar(255) NOT NULL,
	region varchar(50) NOT NULL,
	status varchar(50) NOT NULL,
	owner_type varchar(50) DEFAULT ''::character varying NOT NULL,
	owner_id varchar(255) DEFAULT ''::character varying NOT NULL,
	issuer_url varchar(255) DEFAULT ''::character varying NOT NULL,
	"role" varchar(50) DEFAULT ''::character varying NOT NULL,
	CONSTRAINT chk_public_tenants_schema_name CHECK ((length((schema_name)::text) >= 3)),
	CONSTRAINT uni_public_tenants_id PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_public_tenants_domain_url ON public.tenants USING btree (domain_url);
CREATE UNIQUE INDEX IF NOT EXISTS idx_public_tenants_schema_name ON public.tenants USING btree (schema_name);

-- +goose Down
DROP TABLE IF EXISTS tenants CASCADE;
DROP TABLE IF EXISTS keystore_configurations CASCADE;
