-- This file was generated by GORM DDL
-- +goose Up
CREATE TABLE IF NOT EXISTS certificates (
	id uuid NOT NULL,
	fingerprint text NOT NULL,
	common_name varchar(64) NOT NULL,
	state varchar(255) NULL,
	purpose varchar(255) NULL,
	creation_date timestamptz NOT NULL,
	expiration_date timestamptz NOT NULL,
	cert_pem text NULL,
	private_key_pem text NULL,
	auto_rotate bool DEFAULT true NOT NULL,
	supersedes_id text NULL,
	CONSTRAINT certificates_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events (
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	identifier varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"data" jsonb NOT NULL,
	status varchar(255) NOT NULL,
	previous_item_status varchar(255) NULL,
	CONSTRAINT events_pkey PRIMARY KEY (identifier)
);

CREATE TABLE IF NOT EXISTS "group" (
	id uuid NOT NULL,
	"name" varchar(64) NOT NULL,
	description text NULL,
	"role" varchar(255) NOT NULL,
	iam_identifier varchar(128) NOT NULL,
	CONSTRAINT group_pkey PRIMARY KEY (id),
	CONSTRAINT uni_group_iam_identifier UNIQUE (iam_identifier),
	CONSTRAINT uni_group_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS key_configuration_tags (
	id uuid NOT NULL,
	value varchar(255) NOT NULL,
	CONSTRAINT key_configuration_tags_pkey PRIMARY KEY (id),
	CONSTRAINT uni_key_configuration_tags_value UNIQUE (value)
);

CREATE TABLE IF NOT EXISTS "keys" (
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	id uuid NOT NULL,
	key_configuration_id uuid NOT NULL,
	"name" varchar(255) NOT NULL,
	"key_type" varchar(50) NOT NULL,
	description text NULL,
	algorithm varchar(50) NOT NULL,
	provider varchar(50) NOT NULL,
	region varchar(50) NOT NULL,
	state varchar(50) DEFAULT 'ENABLED'::character varying NOT NULL,
	native_id varchar(255) NULL,
	last_used timestamptz NULL,
	management_access_data jsonb NULL,
	crypto_access_data jsonb NULL,
	is_primary bool NULL,
	CONSTRAINT keys_pkey PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS keyname ON keys USING btree (key_configuration_id, name);

CREATE TABLE IF NOT EXISTS systems (
	id uuid NOT NULL,
	identifier varchar(255) NOT NULL,
	region varchar(50) NOT NULL,
	"type" varchar(50) NOT NULL,
	key_configuration_id uuid NULL,
	status varchar(50) DEFAULT 'DISCONNECTED'::character varying NULL,
	CONSTRAINT systems_pkey PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS region_sys ON systems USING btree (region, identifier);

CREATE TABLE IF NOT EXISTS systems_properties (
	id uuid NOT NULL,
	"key" varchar(255) NOT NULL,
	value varchar(255) NULL,
	CONSTRAINT systems_properties_pkey PRIMARY KEY (id, key)
);

CREATE TABLE IF NOT EXISTS tenant_configs (
	"key" varchar(255) NOT NULL,
	value jsonb NOT NULL,
	CONSTRAINT tenant_configs_pkey PRIMARY KEY (key)
);

CREATE TABLE IF NOT EXISTS workflows (
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	id uuid NOT NULL,
	state varchar(50) NOT NULL,
	initiator_id varchar(255) NOT NULL,
	initiator_name varchar(255) NOT NULL,
	approver_group_ids jsonb NULL,
	artifact_type varchar(50) NOT NULL,
	artifact_id uuid NOT NULL,
	artifact_name varchar(255) NULL,
	action_type varchar(50) NOT NULL,
	parameters text NULL,
	parameters_resource_name varchar(255) NULL,
	parameters_resource_type varchar(50) NULL,
	failure_reason text NULL,
	expiry_date timestamptz NULL,
	CONSTRAINT workflows_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS import_params (
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	key_id uuid NOT NULL,
	wrapping_alg varchar(50) NOT NULL,
	hash_function varchar(50) NOT NULL,
	public_key_pem text NOT NULL,
	expires timestamptz NULL,
	provider_parameters jsonb NULL,
	CONSTRAINT import_params_pkey PRIMARY KEY (key_id),
	CONSTRAINT fk_keys_import_params FOREIGN KEY (key_id) REFERENCES "keys"(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS key_configurations (
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	id uuid NOT NULL,
	"name" varchar(255) NOT NULL,
	description text NULL,
	admin_group_id uuid NOT NULL,
	creator_id varchar(255) NOT NULL,
	creator_name varchar(255) NOT NULL,
	primary_key_id text NULL,
	CONSTRAINT key_configurations_pkey PRIMARY KEY (id),
	CONSTRAINT uni_key_configurations_name UNIQUE (name),
	CONSTRAINT fk_key_configurations_admin_group FOREIGN KEY (admin_group_id) REFERENCES "group"(id)
);

CREATE TABLE IF NOT EXISTS key_labels (
	id uuid NOT NULL,
	"key" varchar(255) NOT NULL,
	value varchar(255) NULL,
	resource_id uuid NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	CONSTRAINT key_labels_pkey PRIMARY KEY (id),
	CONSTRAINT fk_keys_key_labels FOREIGN KEY (resource_id) REFERENCES "keys"(id)
);

CREATE TABLE IF NOT EXISTS key_versions (
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	external_id varchar(255) NOT NULL,
	native_id varchar(255) NULL,
	key_id uuid NOT NULL,
	"version" int8 DEFAULT 0 NOT NULL,
	is_primary bool DEFAULT false NOT NULL,
	CONSTRAINT key_versions_pkey PRIMARY KEY (external_id),
	CONSTRAINT fk_keys_key_versions FOREIGN KEY (key_id) REFERENCES "keys"(id)
);
CREATE UNIQUE INDEX IF NOT EXISTS key_version ON key_versions USING btree (key_id, version);

CREATE TABLE IF NOT EXISTS keyconfigurations_tags (
	key_configuration_tag_id uuid NOT NULL,
	key_configuration_id uuid NOT NULL,
	CONSTRAINT keyconfigurations_tags_pkey PRIMARY KEY (key_configuration_tag_id, key_configuration_id),
	CONSTRAINT fk_keyconfigurations_tags_key_configuration FOREIGN KEY (key_configuration_id) REFERENCES key_configurations(id),
	CONSTRAINT fk_keyconfigurations_tags_key_configuration_tag FOREIGN KEY (key_configuration_tag_id) REFERENCES key_configuration_tags(id)
);

CREATE TABLE IF NOT EXISTS workflow_approvers (
	workflow_id uuid NOT NULL,
	user_id varchar(255) NOT NULL,
	user_name varchar(255) NOT NULL,
	approved bool NULL,
	CONSTRAINT workflow_approvers_pkey PRIMARY KEY (workflow_id, user_id),
	CONSTRAINT fk_workflows_approvers FOREIGN KEY (workflow_id) REFERENCES workflows(id)
);

-- +goose Down
DROP TABLE IF EXISTS workflow_approvers;
DROP TABLE IF EXISTS keyconfigurations_tags;
DROP TABLE IF EXISTS key_versions;
DROP TABLE IF EXISTS key_labels;
DROP TABLE IF EXISTS key_configurations;
DROP TABLE IF EXISTS import_params;
DROP TABLE IF EXISTS workflows;
DROP TABLE IF EXISTS tenant_configs;
DROP TABLE IF EXISTS systems_properties;
DROP TABLE IF EXISTS systems;
DROP TABLE IF EXISTS "keys";
DROP TABLE IF EXISTS key_configuration_tags;
DROP TABLE IF EXISTS "group";
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS certificates;
