package cmkapi

import (
	"database/sql/driver"
	"errors"

	"github.com/openkcm/cmk/utils/enums"
)

// driver.Valuer / sql.Scanner for the persisted cmkapi enum types.
// Valid() is generated by oapi-codegen.

var (
	ErrInvalidKeyState                      = errors.New("invalid key state")
	ErrInvalidSystemStatus                  = errors.New("invalid system status")
	ErrInvalidKeyType                       = errors.New("invalid key type")
	ErrInvalidKeyAlgorithm                  = errors.New("invalid key algorithm")
	ErrInvalidWrappingAlgorithmName         = errors.New("invalid wrapping algorithm name")
	ErrInvalidWrappingAlgorithmHashFunction = errors.New("invalid wrapping algorithm hash function")
)

func (s KeyState) Value() (driver.Value, error) {
	return enums.Value(s, ErrInvalidKeyState)
}

func (s *KeyState) Scan(src any) error {
	return enums.Scan(src, s, ErrInvalidKeyState)
}

func (s SystemStatus) Value() (driver.Value, error) {
	return enums.Value(s, ErrInvalidSystemStatus)
}

func (s *SystemStatus) Scan(src any) error {
	return enums.Scan(src, s, ErrInvalidSystemStatus)
}

func (t KeyType) Value() (driver.Value, error) {
	return enums.Value(t, ErrInvalidKeyType)
}

func (t *KeyType) Scan(src any) error {
	return enums.Scan(src, t, ErrInvalidKeyType)
}

func (a KeyAlgorithm) Value() (driver.Value, error) {
	return enums.Value(a, ErrInvalidKeyAlgorithm)
}

func (a *KeyAlgorithm) Scan(src any) error {
	return enums.Scan(src, a, ErrInvalidKeyAlgorithm)
}

func (a WrappingAlgorithmName) Value() (driver.Value, error) {
	return enums.Value(a, ErrInvalidWrappingAlgorithmName)
}

func (a *WrappingAlgorithmName) Scan(src any) error {
	return enums.Scan(src, a, ErrInvalidWrappingAlgorithmName)
}

func (h WrappingAlgorithmHashFunction) Value() (driver.Value, error) {
	return enums.Value(h, ErrInvalidWrappingAlgorithmHashFunction)
}

func (h *WrappingAlgorithmHashFunction) Scan(src any) error {
	return enums.Scan(src, h, ErrInvalidWrappingAlgorithmHashFunction)
}
