package cmkapi

import (
	"database/sql/driver"
	"errors"

	"github.com/openkcm/cmk/utils/enums"
)

// driver.Valuer / sql.Scanner for KeyState and SystemStatus. Valid() is
// generated by oapi-codegen (see cmkapi.go).

var (
	ErrInvalidKeyState     = errors.New("invalid key state")
	ErrInvalidSystemStatus = errors.New("invalid system status")
)

func (s KeyState) Value() (driver.Value, error) {
	return enums.Value(s, ErrInvalidKeyState)
}

func (s *KeyState) Scan(src any) error {
	return enums.Scan(src, s, ErrInvalidKeyState)
}

func (s SystemStatus) Value() (driver.Value, error) {
	return enums.Value(s, ErrInvalidSystemStatus)
}

func (s *SystemStatus) Scan(src any) error {
	return enums.Scan(src, s, ErrInvalidSystemStatus)
}
