---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tenant-manager.name" . }}-config
  labels:
    {{- include "tenant-manager.labels" . | nindent 4 }}
immutable: {{ .Values.application.isImmutable | default false }}
data:
  config.yaml: |-
    application:
      name: {{ .Chart.Name }}
    {{- with .Values.application }}
      environment: {{ .environment }}
      {{- with .labels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end}}
    {{- end}}

    {{- with .Values.config }}
    {{- toYaml . | nindent 4 }}
    {{- end}}