package db

import (
	"context"
	"errors"

	"github.com/XSAM/otelsql"
	"github.com/openkcm/common-sdk/pkg/commoncfg"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"

	pg "github.com/bartventer/gorm-multitenancy/postgres/v8"

	"github.com/openkcm/cmk/internal/constants"
	"github.com/openkcm/cmk/internal/errs"
	"github.com/openkcm/cmk/internal/log"
)

var ErrWrappingDialectorWithTracing = errors.New("error wrapping dialector with tracing")

// WrapDialectorWithTracing wraps a GORM Dialector with OpenTelemetry tracing.
// Span names are automatically generated by otelsql in the format "sql:<operation>".
// If tracing is disabled or telemetryCfg is nil, the original dialector is returned.
func WrapDialectorWithTracing(
	ctx context.Context,
	dialector gorm.Dialector,
	dsn string,
	telemetryCfg *commoncfg.Telemetry,
) (gorm.Dialector, error) {
	if telemetryCfg == nil || !telemetryCfg.Traces.Enabled {
		return dialector, nil
	}

	// Open a new SQL-DB with otelsql wrapper
	// otelsql.Open automatically instruments all SQL operations with OpenTelemetry traces
	tracedDB, err := otelsql.Open(
		constants.DBDriver,
		dsn,
		otelsql.WithSQLCommenter(false), // Do NOT include query text in spans (security)
	)
	if err != nil {
		return nil, errs.Wrap(ErrWrappingDialectorWithTracing, err)
	}

	// Register DB stats for metrics (optional)
	_, err = otelsql.RegisterDBStatsMetrics(tracedDB)
	if err != nil {
		log.Error(ctx, "failed to register DB stats metrics", err)
	}

	// Inject the traced connection directly into the gorm-multitenancy postgres dialector if possible
	// to preserve multitenancy features.
	if pgDialector, ok := dialector.(*pg.Dialector); ok {
		pgDialector.Conn = tracedDB
		return pgDialector, nil
	}

	// Fallback for non-multitenancy dialectors.
	return postgres.New(postgres.Config{
		Conn: tracedDB,
	}), nil
}
