package db

import (
	"errors"

	"github.com/XSAM/otelsql"
	"github.com/openkcm/common-sdk/pkg/commoncfg"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"

	_ "github.com/lib/pq" // Import PostgreSQL driver

	"github.com/openkcm/cmk/internal/constants"
	"github.com/openkcm/cmk/internal/errs"
)

var (
	ErrWrappingDialectorWithTracing = errors.New("error wrapping dialector with tracing")
)

// WrapDialectorWithTracing wraps a GORM Dialector with OpenTelemetry tracing.
// Span names are automatically generated by otelsql in the format "sql:<operation>".
// If tracing is disabled or telemetryCfg is nil, the original dialector is returned.
func WrapDialectorWithTracing(
	dialector gorm.Dialector,
	dsn string,
	telemetryCfg *commoncfg.Telemetry,
) (gorm.Dialector, error) {
	if telemetryCfg == nil || !telemetryCfg.Traces.Enabled {
		return dialector, nil
	}

	// Open a new SQL-DB with otelsql wrapper
	// otelsql.Open automatically instruments all SQL operations with OpenTelemetry traces
	db, err := otelsql.Open(
		constants.DBDriverName,
		dsn,
		otelsql.WithSQLCommenter(false), // Do NOT include query text in spans (security)
	)
	if err != nil {
		return nil, errs.Wrap(ErrWrappingDialectorWithTracing, err)
	}

	// Register DB stats for metrics (optional, ignore errors)
	_, _ = otelsql.RegisterDBStatsMetrics(db)

	// Create new Postgres dialector with the instrumented DB
	// PreferSimpleProtocol must remain enabled (see dialect/postgres.go)
	return postgres.New(postgres.Config{
		Conn:                 db,
		PreferSimpleProtocol: true,
	}), nil
}
