name: Quality

on:
  push:
    tags:
      - v*
    branches:
      - main
    paths-ignore:
      - 'charts/**'
      - 'docs/**'
      - 'LICENSES/**'
      - '.releases/**'
      - '.github/**'
  pull_request:

permissions:
  contents: read

jobs:
  check:
    uses: openkcm/build/.github/workflows/ci.svc.yaml@main
    with:
      skip_tests: true
    secrets: inherit

  test:
    name: Run Tests using docker
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Tests using docker
        run: |
          make test